default: &default
  adapter: postgresql
  encoding: unicode
  user: lucasrusso
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tweeter_development

test:
  <<: *default
  database: tweeter_test

production:
  <<: *default
  database: tweeter_production
  username: tweeter
  password: <%= ENV["TWEETER_DATABASE_PASSWORD"] %>
